events {}
http {
  server {
    listen 80;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;

    location /api/ {
      proxy_pass http://api:3000/api/;
      proxy_set_header Host $host;
    }

    location /match/ {
      proxy_pass http://api:3000/match/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location / {
      proxy_pass http://web:80;
    }
  }
}
